In [12]:
from glob import glob
import numpy as np 
import cv2

path = 'Data/train/*.jpg'


In [13]:
mean = 0.
std = 0.


In [14]:
for i, image in enumerate(glob(path)):
    img = cv2.imread(image)
    mean += np.mean(img, axis=(0, 1))
    std += np.std(img, axis=(0, 1))

In [15]:
print(mean/i)
print(std/i)

[78.6733784  84.1802572  93.46282555]
[57.9320017  59.22358881 61.1867844 ]


In [19]:
(mean/i)/255


array([0.30852305, 0.33011866, 0.36652088])

In [20]:
(std/i)/255

array([0.22718432, 0.23224937, 0.23994817])